apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx-loadbalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080    # pick any unused port in the 30000–32767 range