apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-loadbalancer-conf
  namespace: default
data:
  nginx.conf: |
    # /etc/nginx/nginx.conf
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      log_format  main  '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent"';

      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      keepalive_timeout  65;

      upstream springboot {
        # point at your springboot Service inside the cluster
        server springboot-service.default.svc.cluster.local:80;
      }

      server {
        listen       80;
        server_name  _;

        location / {
          proxy_pass         http://springboot;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }