spring.application.name=TeamHealthBot
server.port=8001

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://postgres:5432/teamhealthdb
spring.datasource.username=sultan
spring.datasource.password=yourpassword

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Redis
spring.data.redis.host=redis
spring.data.redis.port=6379