apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::989374164925:role/eksctl-teamhealth-eks-nodegroup-ng-NodeInstanceRole-by1iSVOMatTi
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::989374164925:user/sultan1
      username: sultan1
      groups:
        - system:masters
    - userarn: arn:aws:iam::989374164925:root
      username: root
      groups:
        - system:masters