apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-microservice
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cpp-microservice
  template:
    metadata:
      labels:
        app: cpp-microservice
    spec:
      containers:
        - name: cpp-microservice
          image: sultanalzoghaibi/teamhealth-cpp:latest
          imagePullPolicy: Always   # <-- this is key
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-microservice
spec:
  selector:
    app: cpp-microservice
  ports:
    - port: 50051
      targetPort: 50051
  type: ClusterIP