apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpp-microservice
  template:
    metadata:
      labels:
        app: cpp-microservice
    spec:
      containers:
        - name: cpp-microservice
          image: cpp-microservice:latest
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-microservice
spec:
  selector:
    app: cpp-microservice
  ports:
    - port: 50051
      targetPort: 50051
  type: ClusterIP