# springboot-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 30
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: 989374164925.dkr.ecr.us-east-1.amazonaws.com/teamhealth-springboot:latest
          imagePullPolicy: Always  # 👈 ADD THIS LINE
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "250m"       # 0.25 vCPU
              memory: "512Mi"   # 0.5 GB RAM
            limits:
              cpu: "500m"       # 0.5 vCPU
              memory: "1024Mi"  # 1 GB RAM
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/teamhealthdb
            - name: SPRING_DATASOURCE_USERNAME
              value: sultan
            - name: SPRING_DATASOURCE_PASSWORD
              value: yourpassword
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot
  ports:
    - port: 80
      targetPort: 8001
  type: ClusterIP