apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: YOUR_DOCKERHUB_USERNAME/teamhealth-springboot:latest
          ports:
            - containerPort: 8001
          env:
            - name: GRPC_CPP_HOST
              value: grpc-service
            - name: GRPC_CPP_PORT
              value: "50051"