# springboot-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: 989374164925.dkr.ecr.us-east-1.amazonaws.com/teamhealth-springboot:latest
          imagePullPolicy: Always  # 👈 ADD THIS LINE
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "4096Mi"   # 4 GB RAM reserved per pod
              cpu: "2000m"       # 2 full vCPUs reserved per pod
            limits:
              memory: "8192Mi"   # 8 GB RAM max allowed
              cpu: "4000m"       # 4 vCPUs max allowed
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/teamhealthdb
            - name: SPRING_DATASOURCE_USERNAME
              value: sultan
            - name: SPRING_DATASOURCE_PASSWORD
              value: yourpassword
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot
  ports:
    - port: 80
      targetPort: 8001
  type: ClusterIP